Deploy
Cainar/TestGuru pull request #16
Opened 2021-06-05 05:37 UTC by Cainar

2021-06-05 20:51 UTC, BubuntuClu requested changes

2021-06-05 20:51 UTC, BubuntuClu commented on app/controllers/feedback_controller.rb
> +    unless verify_recaptcha
можно было и без полетов в космос сделать контроллер)

2021-06-05 20:51 UTC, BubuntuClu commented on app/controllers/feedback_controller.rb
> +    @target_email = Admin.last.email
это можно указывать в самом мейлере

2021-06-05 20:51 UTC, BubuntuClu commented on app/controllers/feedback_controller.rb
> +  def landing
это метод `new`. не стоит отходить от рест-формата когда в этом нет необходимости

2021-06-05 20:51 UTC, BubuntuClu commented on app/controllers/feedback_controller.rb
> +    respond_to do |format|
я думаю нет смысла делать это блок, когда ты отдаешь всегда только html

2021-06-05 20:51 UTC, BubuntuClu commented on app/controllers/feedback_controller.rb
> +  def set_post
почему пост, почему не фидбэк?

2021-06-05 20:51 UTC, BubuntuClu commented on config/routes.rb
> +  post 'feedback', to: 'feedback#create'
получается обычный ресурс с двумя методами new & create. не стоит изобретать велосипед

2021-06-05 20:51 UTC, BubuntuClu commented on db/migrate/20210409095401_add_name_and_type_attributes_to_users.rb
> +    #remove_column :users, :role , :boolean, :limit => nil
но помни, что так делать нельзя. изменения вносить в смерженные миграции только через новую миграцию

простимо сейчас, так как идет переход на постгрю

2021-06-05 20:51 UTC, BubuntuClu commented on db/migrate/20210123105321_change_role_to_users.rb
> +  	change_column :users, :role, :boolean, using: 'role::boolean', :limit => nil
что тут происходит?)
тебе вообще этот столбец нужен? ты его используешь? админство ты определяешь через тип,а не через это поле

2021-06-07 03:34 UTC, Cainar commented on db/migrate/20210123105321_change_role_to_users.rb
> +  	change_column :users, :role, :boolean, using: 'role::boolean', :limit => nil
Данный столбец удален

2021-06-07 19:44 UTC, BubuntuClu commented on db/migrate/20210607153642_update_foreign_key_in_gists.rb
> +    add_foreign_key :gists, :questions, on_delete: :cascade
это не всегда хорошо. лучше самому управлять поведением через модель.

для ассоциации можно указать опцию `dependent` и у нее есть несколько значений которые описывают как поступать с зависимыми объектами. можно занулять, можно удалять и еще несколько. можно было просто прописать у ассоциаций нужную опцию

2021-06-07 19:44 UTC, BubuntuClu approved these changes

2021-06-07 20:45 UTC, merged