add controller Questions
Cainar/TestGuru pull request #6
Opened 2021-02-07 14:18 UTC by Cainar

2021-02-07 15:12 UTC, Cainar commented on app/models/answer.rb
> +  validate :limit_association, on: :create
Переписал валидацию, старая тоже работала, но на Rusrails.org пишут что, если нужно указать, например от 1 до 4, т.к. ошибка выводится во множественном числе, чтобы сообщение не переписывать, ставят presence: true (если меньше одного ответа, как я понял). Сейчас передал так, что вопрос может быть без ответов. Раньше, проверка отрабатывала неверно в случае если я сразу создавал 4 ответа, валидация не проходит в таком случае. Как я понимаю, ответы должны создаваться по одному.

2021-02-07 15:14 UTC, Cainar commented on db/migrate/20210203184658_add_index_title_level_to_test.rb
> +  	add_index :tests, [:title, :level], unique: true
смерженная миграция, сделал rake db:reset

2021-02-07 18:33 UTC, BubuntuClu requested changes

2021-02-07 18:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +		render plain: @test.questions.pluck(:id, :body)
настрой в IDE отступы в 2 пробела. смотри как все поехало.

2021-02-07 18:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +		params.require(:question).permit(:test_id, :body)
test_id из параметров стоит убрать, так как создавать объекты лучше через ассоциацию

2021-02-07 18:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +		@question = Question.create(question_params)
добавь тут создание через ассоцицию теста

2021-02-07 18:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +	before_action :find_test
тебе на каждый экшен не нужен тест

2021-02-07 18:33 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> + <form action="/tests/1/questions" method="post">
у тебя может не быть теста с таким id, да и для других тестов тоже надо создавать вопросы.
хардкодить ID никогда нельзя. получай id теста из параметров или из объекта теста, который ты нашел в кольбэке

2021-02-07 18:33 UTC, BubuntuClu commented on config/routes.rb
> +  	resources :questions
добавь опцию `shallow: true`

2021-02-07 18:37 UTC, BubuntuClu requested changes

2021-02-07 18:37 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +		@question = Question.create(question_params)
Параметры с фронта могут быть не валидные и тогда у тебя вопрос не будет создан, это надо учитывать

2021-02-08 06:49 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +		@question = Question.create(question_params)
это не исправил. тебе если не придет тело вопроса, то вопрос не будет создан в БД. надо в этом случае вывести сообщение пользователю

2021-02-08 06:51 UTC, BubuntuClu requested changes

2021-02-08 06:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    if @test.present?
как такое может быть? у тебя вопрос обязательно должен быть привязан к тесту

2021-02-08 06:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    if @test.present?
и тем более тут никогда не будет теста, так как ты его не ищешь для этого экшена

2021-02-08 06:51 UTC, BubuntuClu commented on config/routes.rb
> +  resources :tests, shallow: true do
эта опция пишется для вложенных ресурсов

2021-02-08 06:51 UTC, BubuntuClu commented on config/routes.rb
> +  get 'tests/:test_id/questions/:id', to: 'questions#show'
зачем этот путь? у тебя в роутах выше все есть для этого экшена

2021-02-08 07:06 UTC, Cainar commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
Здесь создание через ассоциацию, если я правильно понял

2021-02-08 07:12 UTC, Cainar commented on config/routes.rb
> +  resources :tests, shallow: true do
В руководстве написано: "Также можно определить опцию :shallow в родительском ресурсе, в этом случае все вложенные ресурсы будут мелкие...". Переделал.

2021-02-08 07:26 UTC, Cainar commented on app/controllers/questions_controller.rb
> +		@question = Question.create(question_params)
я переписал это на @question = @test.questions.create(question_params), создается вопрос по пути /tests/:id/questions/new, как я понимаю тело теста обязательно передается? через /questions/new выводится ошибка.

2021-02-08 08:42 UTC, Cainar commented on app/controllers/questions_controller.rb
> +		@question = Question.create(question_params)
Не совсем понимаю как правильно сделать. Добавил If для этого

2021-02-08 09:15 UTC, Cainar commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit([:body])
Unpermitted parameter: :test_id
выводит в косоль, это ошибка, или так должно быть?

2021-02-08 19:06 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> + 		<input type="text" name="question[test_id]" id="question-test_id" value="<%= params[:test_id] %>" type="hidden" style="display: none" >
это поле не нужно, из-за него у тебя строка в консоле про параметр

2021-02-08 19:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    unless @question.new_record?
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2021-02-08 19:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    unless @question.new_record?
старайся по возможности писать условия через if, а не через unless. If воспринимается легче

2021-02-08 20:42 UTC, merged