User authentication
Cainar/TestGuru pull request #9
Opened 2021-04-01 05:11 UTC by Cainar

2021-04-01 18:23 UTC, BubuntuClu requested changes

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:path] = request&.path
имя ключа не говорит о том что это за путь, надо давать более понятные имена.
зачем сохранять путь если ты авторизовался?

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:method] = request&.method
зачем метод сохранять?

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:path] = request&.path
как может быть так что тут не будет `requst` объекта?

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +        if cookies[:method] == 'POST'
вложенные ифы это плохо, как минимум стоит это вынести в метода

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +        if cookies[:method] == 'POST'
можешь привести пример того когда это происходит?

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +          redirect_to cookies[:path]
`redirect_to cookies[:path] || root_path` чтобы избавиться от одного if

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +    session.delete(:user_id)
куку тоже бы очистить

2021-04-01 18:23 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
этот метод не нужен теперь. используй просто `current_user` метод, там где тебе нужен пользователь

2021-04-01 18:23 UTC, BubuntuClu commented on app/views/users/new.html.erb
> +
много пустых строк

2021-04-01 18:23 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирование путей

2021-04-01 18:23 UTC, BubuntuClu commented on db/seeds.rb
> +    password: 'pass3'
форматирование в файле поехало

2021-04-05 08:00 UTC, Cainar commented on app/controllers/application_controller.rb
> +    cookies[:method] = request&.method
Это моя попытка выпольнить пункт из задания:
"6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально"
Изначально использовал redirect_to. Т.к redirect_to  НЕ отправляет POST запрос (т.е. отправляется GET). Нашел гем который выполняет данную функцию (gem 'repost', и метод redirect_post).
Чтобы определить использовать redirect_to или redirect_post я сохраняю метод в куку.

2021-04-05 08:03 UTC, Cainar commented on app/controllers/sessions_controller.rb
> +        if cookies[:method] == 'POST'
У меня root_path это tests#index, на этой странице можно находиться будучи незалогиненным, там же есть возможность начать прохождение теста (кнопка 'Start').
Суть такова, незалогиненный пользователь нажимает СТАРТ, попадает на страницу log_in, после успешного логирования он должен попасть в прохождение теста, т.е. туда, куда изначально намеревался. Если использую redirect_to, то отправляется GET и следовательно  - ошибка, а мне нужен POST. 
Т.о. я определяю какой запрос отправить.

2021-04-05 18:31 UTC, BubuntuClu approved these changes

2021-04-05 18:31 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:user_request_path] = request.path
это все стоит сохранять только если ты не смог пройти аутентификацию, если ты уже залогинен, то тебя сразу пустит туда, куда хотел

2021-04-05 19:10 UTC, merged